---
# tasks file for provision-ec2
- name: Provision {{ tag_name }} in AWS
  ec2:
    instance_tags:
      Name: "{{ tag_name }}"
    key_name: "arth_hadoop_key"
    instance_type: "t2.micro"
    image: "ami-08e0ca9924195beba"
    count: "{{ count }}"
    wait: yes
    vpc_subnet_id: "subnet-ff757197"
    assign_public_ip: yes
    state: present
    region: "ap-south-1"
    group_id: "sg-0304af4788282aea2"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- name: Refresh inventory
  meta: refresh_inventory

