---
# Configuring desired number of webserver instances
- hosts: localhost
  vars:
    count: 2
    tag_name: webserver
  roles:
    - role: roles/provision-ec2
  tasks:
    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        timeout: 180
      loop: "{{ ec2.instances }}"

- hosts: "{{ groups['tag_Name_webserver'] }}"
  roles:
    - role: roles/webserver_role 
